config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories do
      resources :items, except:[:index]
    end
  end


  root to: 'page#index'
  resources :menu, only:[:show]

end

app/models/admin.rb
module Admin
#   def self.table_name_prefix
#     'admin_'
#   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  #associations
  has_many :items, dependent: :destroy
  has_one :document, as: :documentable

  #nested Attributes
  accepts_nested_attributes_for :document , reject_if: :all_blank, allow_destroy: true
end

app/models/document.rb
class Document < ApplicationRecord
  #association
  belongs_to :documentable, polymorphic: true, optional: true

  #paperclip
  has_attached_file :doc
  validates_attachment_content_type :doc, :content_type =>["image/jpg", "image/jpeg", "image/png", "image/gif"]

  #validations
  validates_presence_of :doc
end

app/models/item.rb
class Item < ApplicationRecord
  #associations
  has_many :item_prices, dependent: :destroy
  has_one :document, as: :documentable
  belongs_to :category

  #nested attributes
  accepts_nested_attributes_for :item_prices, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :document , reject_if: :all_blank, allow_destroy: true
end

app/models/item_price.rb
class ItemPrice < ApplicationRecord
  #association
  belongs_to :item
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  #before_action :authenticate_admin!
  layout "admin/layouts/application"
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
    @document = @category.build_document
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_path(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to admin_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to admin_categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, document_attributes: [:doc,:doc_type,:_destroy])
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:new, :edit, :create]


  def show
  end

  def new
    @item = Item.new
    @item.build_document
    @item.item_prices.build
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to admin_category_path(@category), notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to admin_category_path(@item.category), notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to admin_category_path(@item.category), notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description, :category_id, document_attributes: [:doc, :doc_type, :_destroy], item_prices_attributes: [:price, :quantity, :size, :_destroy])
    end

    def set_category
      @category = Category.find(params[:category_id])
    end
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < Admin::BaseController
  before_action :set_admin_menu, only: [:show, :edit, :update, :destroy]

  def index
    @admin_menus = Menu.all
  end

  def show
  end

  def new
    @admin_menu = Menu.new
  end

  def edit
  end

  def create
    @admin_menu = Menu.new(admin_menu_params)

    respond_to do |format|
      if @admin_menu.save
        format.html { redirect_to @admin_menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @admin_menu }
      else
        format.html { render :new }
        format.json { render json: @admin_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin_menu.update(admin_menu_params)
        format.html { redirect_to @admin_menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_menu }
      else
        format.html { render :edit }
        format.json { render json: @admin_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin_menu.destroy
    respond_to do |format|
      format.html { redirect_to admin_menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_admin_menu
      @admin_menu = Menu.find(params[:id])
    end

    def admin_menu_params
      params.permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_header

  def set_header
    @menu_category = Category.all
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @items = @category.items
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/admin/categories/_form.html.erb
<div class="card-body card-block">
  <%= form_with(model: [:admin, category], local: true) do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this menu category from being saved:</h2>

        <ul>
          <% category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-12">
        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>
      </div>

      <div class="col-md-12">
          <%= form.fields_for :document do |f| %>
            <div class="field">
              <%= f.label :documents %>
              <%= f.file_field :doc, class: "form-control" %>
            </div>
          <% end  %>
      </div>
    </div>

    <div class="card-footer card-actions">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<div class="container col-md-12">

  <div class="card">
    <div class="card-header">
      <strong class="card-title">Edit Menu Category</strong>
      <strong class="card-actions"><%= link_to 'Back', admin_categories_path %></strong>

    </div>

    <%= render 'form', category: @category %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container bounceInRight">
  <div class="card">
    <div class="card-header">
      <strong class="card-title">Menu Items</strong>
      <strong class="card-actions">
        <%= link_to 'New Category', new_admin_category_path %>
      </strong>
    </div>
    <div class="card-body">
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>

        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= link_to '', admin_category_path(category), class: 'btn btn-info btn-sm fa fa-eye' %></td>
            <td><%= link_to '', edit_admin_category_path(category), class: 'btn btn-warning btn-sm fa fa-pencil' %></td>
            <td><%= link_to '', admin_category_path(category), class: 'btn btn-danger btn-sm fa fa-trash' ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br>

app/views/admin/categories/new.html.erb
<div class="container col-md-12">

  <div class="card">
    <div class="card-header">
      <strong class="card-title">Create Menu Category</strong>
      <strong class="card-actions"><%= link_to 'Back', admin_categories_path %></strong>

    </div>

    <%= render 'form', category: @category %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<div class="container bounceInRight">
  <div class="card">
    <div class="card-header">
      <strong class="card-title">
        <%= @category.name %>
        <%= link_to 'Edit', edit_admin_category_path(@category) %>
      </strong>
      <strong class="card-actions">
        <%= link_to 'new menu item', new_admin_category_item_path(@category) %>
      </strong>
    </div>
    <div class="card-body">
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @category.items.each do |item| %>
          <tr>
            <td><%= item.name %></td>
            <td><%= item.description %></td>
            <td><%= link_to '', admin_category_item_path(@category,item), class: 'btn btn-info btn-sm fa fa-eye' %></td>
            <td><%= link_to '', edit_admin_category_item_path(@category,item), class: 'btn btn-warning btn-sm fa fa-pencil' %></td>
            <td><%= link_to '', admin_category_item_path(@category,item), class:'btn btn-danger btn-sm fa fa-trash', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to 'Back', admin_categories_path %>
    </div>
  </div>
</div>
<br>

app/views/admin/items/_form.html.erb
<div class="card-body card-block">
  <%= form_with(model: [:admin, @category, item], local: true) do |form| %>
    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %> prohibited this menu item from being saved:</h2>

        <ul>
          <% item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.hidden_field :category_id, :value => @category.id  %>

    <div class="row">

      <div class="col-md-12">
        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

      </div>
      <div class="col-md-12">
        <div class="field">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form-control" %>
        </div>
      </div>


        <%= form.fields_for :item_prices do |f| %>
        <div class="col-md-12">
          <div class="field">
            <%= f.label :price %>
            <%= f.number_field :price, class: "form-control" %>
          </div>
          <div class="field ">
            <%= f.label :size %>
            <%= f.text_field :size, class: "form-control" %>
          </div>
          <div class="field">
            <%= f.label :quantity %>
            <%= f.text_field :quantity, class: "form-control" %>
          </div>
        </div>

        <% end  %>

        <div class="container">
          <%= link_to_add_association 'add prices', form, :item_prices, class:"form-group" %>
        </div>

      <div class="col-md-12">
        <%= form.fields_for :document do |f| %>
          <div class="field">
            <%= f.label :documents %>
            <%= f.file_field :doc, class: "form-control" %>
          </div>
        <% end  %>
      </div>
    </div>

    <div class="card-footer card-actions">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/items/_item_price_fields.html.erb
<div class="col-md-12">
<div class="field">
  <%= f.label :price %>
  <%= f.number_field :price, class: "form-control" %>
</div>
<div class="field ">
  <%= f.label :size %>
  <%= f.text_field :size, class: "form-control" %>
</div>
<div class="field">
  <%= f.label :quantity %>
  <%= f.text_field :quantity, class: "form-control" %>
</div>
</div>

app/views/admin/items/edit.html.erb
<div class="container col-md-12">

  <div class="card">
    <div class="card-header">
      <strong class="card-title">Edit Menu Items</strong>
      <strong class="card-actions"><%= link_to 'Back', admin_category_path(@item.category) %></strong>

    </div>

    <%= render 'form', item: @item %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container col-md-12">

  <div class="card">
    <div class="card-header">
      <strong class="card-title">Create Menu Items</strong>
      <strong class="card-actions"><%= link_to 'Back', admin_category_path(@category) %></strong>

    </div>
    <%= render 'form', item: @item %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container bounceInRight">
  <div class="card">
    <div class="card-header">
      <strong class="card-title">
        <%= @item.name %>
      </strong>
      <strong class="card-actions">
        <%= link_to 'Edit', edit_admin_category_item_path(@item.category, @item) %>
      </strong>
    </div>
    <div class="card-body">
      <strong>Description:</strong>
      <%= @item.description %>
    </div>
  </div>
  <strong class="card-actions">
    <%= link_to 'Back', admin_category_path(@item.category) %>
  </strong>
</div>

app/views/admin/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>">
    <!-- Below methood is used to apply the close property to our flash -->
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/admin/layouts/_header.html.erb
<header id="header" class="header">

<!--  <div class="header-menu">-->

<!--    <div class="col-sm-7">-->
<!--      <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>-->
<!--      <div class="header-left">-->
<!--        <button class="search-trigger"><i class="fa fa-search"></i></button>-->
<!--        <div class="form-inline">-->
<!--          <form class="search-form">-->
<!--            <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">-->
<!--            <button class="search-close" type="submit"><i class="fa fa-close"></i></button>-->
<!--          </form>-->
<!--        </div>-->

<!--        <div class="dropdown for-notification">-->
<!--          <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--            <i class="fa fa-bell"></i>-->
<!--            <span class="count bg-danger">5</span>-->
<!--          </button>-->
<!--          <div class="dropdown-menu" aria-labelledby="notification">-->
<!--            <p class="red">You have 3 Notification</p>-->
<!--            <a class="dropdown-item media bg-flat-color-1" href="#">-->
<!--              <i class="fa fa-check"></i>-->
<!--              <p>Server #1 overloaded.</p>-->
<!--            </a>-->
<!--            <a class="dropdown-item media bg-flat-color-4" href="#">-->
<!--              <i class="fa fa-info"></i>-->
<!--              <p>Server #2 overloaded.</p>-->
<!--            </a>-->
<!--            <a class="dropdown-item media bg-flat-color-5" href="#">-->
<!--              <i class="fa fa-warning"></i>-->
<!--              <p>Server #3 overloaded.</p>-->
<!--            </a>-->
<!--          </div>-->
<!--        </div>-->

<!--        <div class="dropdown for-message">-->
<!--          <button class="btn btn-secondary dropdown-toggle" type="button"-->
<!--                  id="message"-->
<!--                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--            <i class="ti-email"></i>-->
<!--            <span class="count bg-primary">9</span>-->
<!--          </button>-->
<!--          <div class="dropdown-menu" aria-labelledby="message">-->
<!--            <p class="red">You have 4 Mails</p>-->
<!--            <a class="dropdown-item media bg-flat-color-1" href="#">-->
<!--              <span class="photo media-left"><img alt="avatar" src="images/avatar/1.jpg"></span>-->
<!--              <span class="message media-body">-->
<!--                                    <span class="name float-left">Jonathan Smith</span>-->
<!--                                    <span class="time float-right">Just now</span>-->
<!--                                        <p>Hello, this is an example msg</p>-->
<!--                                </span>-->
<!--            </a>-->
<!--            <a class="dropdown-item media bg-flat-color-4" href="#">-->
<!--              <span class="photo media-left"><img alt="avatar" src="images/avatar/2.jpg"></span>-->
<!--              <span class="message media-body">-->
<!--                                    <span class="name float-left">Jack Sanders</span>-->
<!--                                    <span class="time float-right">5 minutes ago</span>-->
<!--                                        <p>Lorem ipsum dolor sit amet, consectetur</p>-->
<!--                                </span>-->
<!--            </a>-->
<!--            <a class="dropdown-item media bg-flat-color-5" href="#">-->
<!--              <span class="photo media-left"><img alt="avatar" src="images/avatar/3.jpg"></span>-->
<!--              <span class="message media-body">-->
<!--                                    <span class="name float-left">Cheryl Wheeler</span>-->
<!--                                    <span class="time float-right">10 minutes ago</span>-->
<!--                                        <p>Hello, this is an example msg</p>-->
<!--                                </span>-->
<!--            </a>-->
<!--            <a class="dropdown-item media bg-flat-color-3" href="#">-->
<!--              <span class="photo media-left"><img alt="avatar" src="images/avatar/4.jpg"></span>-->
<!--              <span class="message media-body">-->
<!--                                    <span class="name float-left">Rachel Santos</span>-->
<!--                                    <span class="time float-right">15 minutes ago</span>-->
<!--                                        <p>Lorem ipsum dolor sit amet, consectetur</p>-->
<!--                                </span>-->
<!--            </a>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="dropdown for-message">-->
          <%# if user_signed_in? %>
              <%#= link_to('Logout', destroy_user_session_path, method: :delete) %>
          <%# else %>
              <%#= link_to('Login', new_user_session_path) %>
          <%# end %>
<!--        </div>-->
<!--      </div>-->

<!--    </div>-->

<!--    <div class="col-sm-5">-->
<!--      <div class="user-area dropdown float-right">-->
<!--        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
          <%# image_tag "admin.jpg", class:"user-avatar rounded-circle"  %>

<!--        </a>-->

<!--        <div class="user-menu dropdown-menu">-->
<!--          <a class="nav-link" href="#"><i class="fa fa- user"></i>My Profile</a>-->

<!--          <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>-->

<!--          <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>-->

<!--          <a class="nav-link" href="#"><i class="fa fa-power -off"></i>Logout</a>-->
<!--        </div>-->
<!--      </div>-->

<!--      <div class="language-select dropdown" id="language-select">-->
<!--        <a class="dropdown-toggle" href="#" data-toggle="dropdown"  id="language" aria-haspopup="true" aria-expanded="true">-->
<!--          <i class="flag-icon flag-icon-us"></i>-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="language" >-->
<!--          <div class="dropdown-item">-->
<!--            <span class="flag-icon flag-icon-fr"></span>-->
<!--          </div>-->
<!--          <div class="dropdown-item">-->
<!--            <i class="flag-icon flag-icon-es"></i>-->
<!--          </div>-->
<!--          <div class="dropdown-item">-->
<!--            <i class="flag-icon flag-icon-us"></i>-->
<!--          </div>-->
<!--          <div class="dropdown-item">-->
<!--            <i class="flag-icon flag-icon-it"></i>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->

<!--    </div>-->
<!--  </div>-->

</header><!-- /header -->

app/views/admin/layouts/_side_bar.html.erb
<aside id="left-panel" class="left-panel">
  <nav class="navbar navbar-expand-sm navbar-default">

    <div class="navbar-header">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand" href="/"></a>
      <a class="navbar-brand hidden" href="/"></a>
    </div>

    <div id="main-menu" class="main-menu collapse navbar-collapse">
      <ul class="nav navbar-nav">
<!--        <li>-->
<!--          <a href="/"> <i class="menu-icon fa fa-dashboard"></i>Dashboard </a>-->
<!--        </li>-->
        <li>
          <%= link_to admin_categories_path do %><i class="menu-icon fa fa-delicious"></i> Report<%end %>
        </li>
<!--        <li>-->
<!--          <%#= link_to new_admin_report_path do %><i class="menu-icon fa fa-area-chart"></i> New Report<%#end %>-->
<!--        </li>-->
<!--        <li>-->
<!--          <%#= link_to admin_users_path do %><i class="menu-icon fa fa-users"></i> Users<%#end %>-->
<!--        </li>-->
<!--        <li>-->
<!--          <%#= link_to new_admin_user_path do %><i class="menu-icon fa fa-user-circle-o"></i> New User<%#end %>-->
<!--        </li>-->
<!--        <li>-->
<!--          <%#= link_to admin_announcements_path do %> <i class="menu-icon fas fa-bullhorn"></i> Announcements <%# end %>-->
<!--        </li>-->
<!--        <li>-->
<!--          <%#= link_to admin_sites_path do %> <i class="menu-icon fas fa-bullhorn"></i> Sites <%# end %>-->
<!--        </li>-->
<!--        <li>-->
<!--          <%#= link_to admin_links_path do %> <i class="menu-icon fas fa-bullhorn"></i> Links <%# end %>-->
<!--        </li>-->
<!--        <li>-->
<!--          <%# link_to admin_categories_path do %> <i class="menu-icon fas fa-bullhorn"></i> Category <%# end %>-->
<!--        </li>-->


      </ul>
    </div>
  </nav>
</aside>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">
    <title>Admin Panel</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => true %>
  </head>
  <body style="background-color: #FFFFFF">
    <%= render 'admin/layouts/side_bar' %>
    <div id="right-panel" class="right-panel">
      <%= render 'admin/layouts/header' %>
      <%= yield %>
    </div>
    <%= render "admin/layouts/flash" %>
  </body>
</html>

app/views/layouts/_header.html.erb
<header class="soufle-header-site soufle-header-type-1 soufle-sticky-header-on">
  <div class="soufle-nav-wrap soufle-nav-left">
    <nav class="soufle-site-navigation primary-navigation" id="soufle-menu-primary">
      <ul class="soufle-nav-menu">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onClick="window.location = '#'">OUR STORY</a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li>
              <a class="dropdown-item" href="#">OUR COFFEE</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">OUR SOUFFLÉ</a>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" id="menuDropdownMenuLink"
             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            OUR MENU
          </a>
          <ul class="dropdown-menu food-menu" aria-labelledby="menuDropdownMenuLink">

            <% if @menu_category  %>
            <% @menu_category.each do |category| %>
              <li>
                <%= link_to category.name, menu_path(category.id) %>
              </li>
            <% end  %>
            <% else  %>
              <li> No menu </li>
            <% end %>
<!--            <li><a class="dropdown-item" href="frappes.html">FRAPPÉS</a></li>-->
<!--            <li><a class="dropdown-item" href="milkshakes.html">MILKSHAKES</a></li>-->
<!--            <li><a class="dropdown-item" href="smoothies.html">SMOOTHIES</a></li>-->
<!--            <li><a class="dropdown-item" href="#">SANDWICHES & SNACKS</a></li>-->
<!--            <li><a class="dropdown-item" href="ice-cream.html">ICE CREAM</a></li>-->
<!--            <li><a class="dropdown-item" href="extras.html">EXTRAS</a></li>-->
          </ul>
        </li>
        <li><a href="#">SO SOUFFLÉ</a></li>
      </ul>
    </nav>
  </div>
  <!--Logo-->
  <div class="soufle-wrap-logo">
    <a class="soufle-logo" href="<%= root_path %>">
      <img src="<%= asset_url("new_logo_so_souffle.png") %>" alt="Logo"/>
    </a>
  </div>
  <div class="soufle-nav-wrap soufle-nav-right">
    <nav class="soufle-site-navigation secondary-navigation" id="soufle-menu-secondary">
      <ul class="soufle-nav-menu">
        <li><a href="#">STORES</a></li>
        <li><a href="#">TESTIMONIALS</a></li>
        <li><a href="#">CONTACT US</a></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>So Soufflé | So Rich, So Smooth, So Good</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div>
      <div class="spinner">
          <div class="line1"></div>
          <div class="line2"></div>
          <div class="line3"></div>
          <div class="line4"></div>
      </div>
      <div id="page" class="hfeed site invisible">
          <%= render 'layouts/header' %>
          <%= yield %>
          <%= render 'layouts/footer' %>
      </div>
   </div>
  </body>
</html>